export const THEATER_RESPONSE={
    GET_ALL_THEATER:'THEATER FATCH  SUCCESSFULLY',
    ERROR_GET_ALL_THEATER:'ERROR RETRIEVING THEATER',
    GET_THEATER_BY_ID:'THEATER FATCH  SUCCESSFULLY',
    ERROR_THEATER_BY_ID:'ERROR RETRIEVING THEATER ',
    ADD_THEATER:'ADD THEATER SUCCESSFULLY',
    ERROR_ADD_THEATER:'ERROR TO ADD THEATER',
    UPDATE_THEATER:'THEATER UPDATE SUCCESSFULLY',
    ERROR_UPDATE_THEATER:'ERROR TO UPDATE THEATER',
    DELETE_THEATER:'THEATER DELETE SUCCESSFULLY',
    ERROR_DELETE_THEATER:'ERROR TO DELETE THEATER',
    THEATER_NOT_FOUND:'THEATER NOT FOUND',
    NOT_AUTHORIZED:'YOU ARE NOT VALID USER FOR THIS ACTION!'

}

export const jwtConstants={
    SECRET:'thesecretkey' 
}
