export const RATING_RESPONSE={
    ADD_RATING:'RATING ADD SUCCESSFULLY',
    EEROR_ADD_RATING:'ERROR TO ADDING RATING',
    UPDATE_RATING:'RATING UPDATE SUCCESSFULLY',
    ERROR_UPDATE_RATING:'ERROR TO UPDATE RATING',
    DELETE_RATING:'RATING DELETE SUCCESSFULLY',
    ERROR_DELETE_RATING:'ERROR TO DELETE RATING',
}