export const MOVIE_RESPONSE={
    GET_ALL_MOVIE:'ALL MOVIE FATCH  SUCCESSFULLY',
    ERROR_GET_ALL_MOVIE:'ERROR RETRIEVING ALL MOVIE',
    GET_MOVIE_BY_ID:'MOVIE FATCH  SUCCESSFULLY',
    ERROR_MOVIE_BY_ID:'ERROR RETRIEVING MOVIE ',
    ADD_MOVIE:'ADD MOVIE SUCCESSFULLY',
    ERROR_ADD_MOVIE:'ERROR TO ADD MOVIE',
    UPDATE_MOVIE:'MOVIE UPDATE SUCCESSFULLY',
    ERROR_UPDATE_MOVIE:'ERROR TO UPDATE MOVIE',
    DELETE_MOVIE:'MOVIE DELETE SUCCESSFULLY',
    ERROR_DELETE_MOVIE:'ERROR TO DELETE MOVIE',
    MOVIE_NOT_FOUND:'MOVIE NOT FOUND',
    MOVIE_FOUND:'MOVIE FOUND SUCCESSFULLY',
    NOT_AUTHORIZED:'YOU ARE NOT VALID USER FOR THIS ACTION!'
}

export const jwtConstants={
    SECRET:'thesecretkey' 
}
